### ISSUE TITLE
time_crypt seal algorithm?

### ISSUE THREAD

**Issue by vkobel** [mikelodder7/blsful#12]
Hello, thanks for this great repo.

What is the algorithm used for the seal and unseal functions in `src/traits/time_crypt.rs`?
Was it part the audit?

Many thanks.

**Comment by mikelodder7** [comment]
[tlock: Practical Timelock Encryption from Threshold BLS](https://eprint.iacr.org/2023/189.pdf)

Yes it was part of the audit.

**Comment by vkobel** [comment]
Was it implemented from "algorithm 1" page 11 directly? I see the notation differs a bit (eg. `K = e(A^r, HG2(ρ))` vs `PKρ ← e(P, H1(ρ))`)

**Comment by vkobel** [comment]
A difference I see is the [use of an XOF (shake128)](https://github.com/hyperledger-labs/agora-blsful/blob/49827e21b98902e686dcb39aa2c64a1716988257/src/traits/time_crypt.rs#L137) to match the message length. 

Whereas tlock is using [key encapsulation/wrapping through age ](https://github.com/drand/tlock/blob/543b49765bdec12a93f3bd624d7e7c008183cfc6/tlock_age.go#L27)

Just wondering if it's simply a design choice?

**Comment by mikelodder7** [comment]
If you look at the paper, they use XOR instead of blending it like ECIES. I kept to the basics of just doing as the paper suggests making it easier for consumers to apply their own ECIES like patterns. I used XOF because it allows extracting the exact number of bytes necessary to XOR against the input. Otherwise I need to use a fixed digest multiple times to accomplish the same task.
